name: Envoxy model enforcement

on: [pull_request]

jobs:
  validate-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: python -m pip install -r requirements.dev || true
      - name: Validate JSON models
        run: python -m envoxy.tools.validate_models src/muzzley/data-layer/models
      - name: Check migrations
        run: |
          set -euo pipefail
          # Prefer framework-level migrations; fall back to examples per-service
          # Prefer packaged framework versions (installed package) via importable path
          FRAMEWORK_VERSIONS=src/envoxy/tools/alembic/alembic/versions
          if [ -d "$FRAMEWORK_VERSIONS" ]; then
            python -m envoxy.tools.check_migrations "$FRAMEWORK_VERSIONS"
          else
            echo "No framework migrations at $FRAMEWORK_VERSIONS; skipping"
          fi

          # Check any per-service migrations under examples/
          for d in examples/*/alembic/versions; do
            if [ -d "$d" ]; then
              python -m envoxy.tools.check_migrations "$d"
            fi
          done
      - name: Run tests
        run: pytest -q
